SELECT CURRENT_DATE FROM DUAL;

SELECT CURRENT_TIME FROM DUAL;

SELECT CURRENT_TIMESTAMP FROM DUAL;

SELECT DATE(CURRENT_TIMESTAMP) FROM DUAL;

CREATE TABLE mes(
	id INT,
	content VARCHAR(30),
	send_time DATETIME);
INSERT INTO mes VALUES
	(1,'北京新闻',CURRENT_TIMESTAMP),
	(2,'上海新闻',NOW()),
	(3,'广州新闻',NOW());
SELECT * FROM mes;

SELECT NOW()FROM DUAL;

SELECT id,content,DATE(send_time) FROM mes;

SELECT * FROM mes WHERE DATE_ADD(send_time,INTERVAL 10 MINUTE)> NOW();
SELECT * FROM mes WHERE DATE_SUB(NOW(),INTERVAL 20 MINUTE) < send_time;

SELECT DATEDIFF('2011-11-11','1990-01-01') FROM DUAL;

SELECT DATEDIFF(NOW(),'2000-11-09') FROM DUAL;

SELECT DATEDIFF(DATE_ADD('2000-11-09',INTERVAL 80 YEAR),NOW()) AS haslife FROM DUAL;